routes/klienci.py
from flask import Blueprint, request, Response, abort, jsonify, render_template, g, flash, redirect, url_for
from connection.database import Database
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from lib.config import app_config
klienci_route = Blueprint('klienci_route', __name__)
klienci_route.config = app_config()['secret']
class NowyKlient(FlaskForm):
    imie = StringField('Imie')
    nazwisko = StringField('Nazwisko')
    nr_telefonu = StringField('Nr telefonu')
    adres = StringField('Adres')
    kod_pocztowy = StringField('Kod Pocztowy')
    miasto = StringField('Miasto')
    mail = StringField('Email')
    submit = SubmitField("Submit")
@klienci_route.route("/klienci", methods=['POST', 'GET', 'UPDATE', 'DELETE'])
def lista_klientow():
    """
    Route do obslugi tabeli klientow. W zaleznosci od metody sa wykonywane rozne akcje:
    - UPDATE: zaktualizuj klienta w bazie
    """
    t = request.values
    form = NowyKlient()
    edit_form = NowyKlient()
    current_url = request.path
    if "edit" in t.keys():
        print("jestem w edit")
        print(t['edit'])
        if t['edit'] == 'True':
            if edit_form.validate_on_submit():
                return "teraz jestem w edit"
        else:
            if form.validate_on_submit():
                if form.data:
                    dane_klienta = form.data
                    query = "insert into klienci(imie,nazwisko,nr_telefonu,adres,kod_pocztowy,miasto,email) values('{}','{}','{}','{}','{}','{}','{}')".format(
                        dane_klienta['imie'],
                        dane_klienta['nazwisko'],
                        dane_klienta['nr_telefonu'],
                        dane_klienta['adres'],
                        dane_klienta['kod_pocztowy'],
                        dane_klienta['miasto'],
                        dane_klienta['mail']
                    )
                    db_ = Database()
                    db = getattr(g,"db",None)
                    result = db_.exec_query(query=query,type="insert", cnx=db)
                    if result:
                        flash("Klient został zapisany", "success")
                    else:
                        flash("Klient nie został zapisany", "error")
                return redirect(url_for("klienci_route.lista_klientow"))
    if request.method == "GET":
        db_ = Database()
        db = getattr(g, 'db', None)
        # db.connect_to_database()
        query = "SELECT * FROM klienci"
        result = db_.exec_query(query, "select", db)
        # dicts_from_result = [{row[0]: row[1:]} for row in result.fetchall()]
        result_fetch = result.fetchall()
        kolumny = ['id', 'Imie', 'Nazwisko', 'Nr telefonu', 'Adres', 'Kod pocztowy', 'Miasto', 'Email', 'Akcje']
        return render_template("klienci.html", current_url=current_url, kolumny=kolumny,
                               klienci=result_fetch, form=form, edit_form=edit_form)



@klienci_route.route("/usun_klienta", methods=['GET','POST'])
def usun_klienta():
    t = request.values
    if t:
        db_ = Database()
        db = getattr(g, 'db', None)
        query = "delete from klienci where id={}".format(t['id'])
        result = db_.exec_query(cnx=db, query=query, type="delete")
        if result:
            flash("Klient został usuniety", "success")
        else:
            flash("Klient nie został usuniety", "error")
    return redirect(url_for("klienci_route.lista_klientow"))

# @klienci_route.route("/edytuj_klienta", methods=['GET,POST'])
# def edytuj_klienta():
#     # pobierz dane po id
#     if method
#     # wygeneruj modal
#     # zapisz do bazy

    # return "dupa"
@klienci_route.route("/pokaz_zamowienia_dla_klienta")
def zamowienia_per_klient():
    pass

routes/serwis.py
from flask import Blueprint, request, Response, abort, jsonify, render_template, g, flash, redirect, url_for
from connection.database import Database
from wtforms import StringField, SubmitField, SelectField, DateField
from flask_wtf import FlaskForm


serwisy_route = Blueprint("serwisy_route", __name__)



class NowySerwis(FlaskForm):
    urzadzenie = SelectField("Urządzenie")
    data_serwisu = DateField("Data Serwisu")
    rodzaj_serwisu = StringField("Rodzaj serwisu")
    submit = SubmitField("Submit")




@serwisy_route.route("/serwisy", methods=['POST', 'GET'])
def lista_serwisu():
    t = request.values
    current_url = request.path
    form = NowySerwis()
    db_ = Database()
    db = getattr(g, 'db', None)
    query_urzadzenia = "select id, numer from urzadzenia"
    result_lista = db_.exec_query(query_urzadzenia, "select", db)
    form.urzadzenie.choices = result_lista.fetchall()
    if form.validate_on_submit():
        if form.data:
            serwis_data = form.data
            query = "insert into serwis(id_urzadzenia,data_serwisu,rodzaj_serwisu) values ('{}','{}','{}')".format(
                int(serwis_data['urzadzenie']),
                serwis_data['data_serwisu'],
                serwis_data['rodzaj_serwisu']
            )
            ins = db_.exec_query(query,"insert",db)
            if ins:
                flash("Serwis został zapisany", "success")
            else:
                flash("Serwis nie został zapisany", "error")
            return redirect(url_for("serwisy_route.lista_serwisu"))
    query = "select serwis.id, urzadzenia.numer, serwis.data_serwisu, serwis.rodzaj_serwisu from serwis join urzadzenia on serwis.id_urzadzenia=urzadzenia.id"
    result = db_.exec_query(query,"select",db)
    kolumny = ['id', "Urządzenie", "Data serwisu", "Rodzaj serwisu", "Akcje"]
    return render_template("serwis.html", form=form, current_url=current_url, serwisy=result.fetchall(), kolumny=kolumny)

@serwisy_route.route("/usun_serwis",methods=['GET','POST'])
def usun_serwis():
    t = request.values
    if t:
        db_ = Database()
        db = getattr(g, 'db', None)
        query = "delete from serwis where id={}".format(t['id'])
        result = db_.exec_query(cnx=db, query=query, type="delete")
        if result:
            flash("Serwis został usuniety", "success")
        else:
            flash("Serwis nie został usuniety", "error")
        return redirect(url_for("serwisy_route.lista_serwisu"))

routes/urzadzenia.py
from flask import Blueprint, request, render_template, g, flash, redirect, url_for
from connection.database import Database
from wtforms import StringField, SubmitField
from flask_wtf import FlaskForm

urzadzenia_route = Blueprint("urzadzenia_route", __name__)


class NoweUrzadzenie(FlaskForm):
    producent = StringField("Producent")
    model = StringField("Model")
    numer = StringField("Numer")
    submit = SubmitField("Submit")


@urzadzenia_route.route("/urzadzenia",methods=['POST', 'GET', 'UPDATE', 'DELETE'])
def lista_urzadzen():
    form = NoweUrzadzenie()
    current_url = request.path
    db_ = Database()
    db = getattr(g, 'db', None)
    query = "SELECT * FROM urzadzenia"
    result = db_.exec_query(query,"select",db)
    if form.validate_on_submit():
        dane_urzadzenia = form.data
        query= "insert into urzadzenia(producent,model,numer) values('{}','{}','{}')".format(
            dane_urzadzenia['producent'],
            dane_urzadzenia['model'],
            dane_urzadzenia['numer']
        )
        result = db_.exec_query(query,"insert",db)
        if result:
            flash("Urządzenie zostało zapisane", "success")
        else:
            flash("Urządzenie nie zostało zapisane", "error")
        return redirect(url_for("urzadzenia_route.lista_urzadzen"))
    kolumny = ['id','Producent','Model','Numer', 'Akcje']
    return render_template("szyny.html", current_url=current_url,urzadzenia=result.fetchall(), kolumny=kolumny,form=form)

@urzadzenia_route.route("/usun_urzadzenie", methods=['GET','POST'])
def usun_urzadzenie():
    t = request.values
    if t:
        db_ = Database()
        db = getattr(g, 'db', None)
        query = "delete from urzadzenia where id={}".format(t['id'])
        result = db_.exec_query(cnx=db, query=query, type="delete")
        if result:
            flash("Urządzenie zostało usuniętę", "success")
        else:
            flash("Urządzenie nie zostało usuniętę", "error")
    return redirect(url_for("urzadzenia_route.lista_urzadzen"))

routes/zamowienia.py
from flask import Blueprint, request, g, flash, redirect, url_for, render_template, send_file

import umowa_gen
from connection.database import Database
from wtforms import StringField, SubmitField, SelectField, DateField
from flask_wtf import FlaskForm

zamowienia_route = Blueprint("zamowienia_route", __name__)


class NoweZamowienie(FlaskForm):
    klient = SelectField("Klient")
    urzadzenie = SelectField("Urządzenie")
    dostawa = SelectField("Rodzaj dostawy", choices=[('kurier', 'Kurier'), ('odbiór osobisty', 'Odbiór osobisty')])
    data_rozpoczenia_wypozyczenia = DateField("Data rozpoczęcia wypożyczenia", format='%Y-%m-%d')
    data_zakonczenia_wypozyczenia = DateField("Data zakończenia wypożyczenia", format='%Y-%m-%d')
    rodzaj_platnosci = SelectField("Rodzaj płatności", choices=[("gotowka", "Gotówka"), ("przelew", "Przelew")])
    submit = SubmitField("Submit")


@zamowienia_route.route("/zamowienie", methods=['POST', 'GET'])
def lista_zamowien():
    form = NoweZamowienie()
    current_url = request.path
    db_ = Database()
    db = getattr(g, 'db', None)

    query_urzadzenia = "select id, numer from urzadzenia"
    result_lista_urzadzenia = db_.exec_query(query_urzadzenia, "select", db)

    query_klient = "select id, nazwisko from klienci"
    result_lista_klient = db_.exec_query(query_klient, "select", db)

    form.urzadzenie.choices = result_lista_urzadzenia.fetchall()
    form.klient.choices = result_lista_klient.fetchall()

    query = "SELECT wypozyczenia.id,nazwisko,numer,dostawa,data_rozpoczecia_wypozyczenia,data_zakonczenia_wypozyczenia, rodzaj_platnosci FROM wypozyczenia join klienci on wypozyczenia.id_klienta=klienci.id join urzadzenia on wypozyczenia.id_urzadzenia=urzadzenia.id"
    kolumny = ['id', 'Klient', 'Urządzenie', 'Rodzaj dostawy', "Data rozpoczęcia wypożyczenia",
               "Data zakończenia wypożyczenia", "Rodzaj płatności", "Akcje"]
    result_zamowienia = db_.exec_query(query, "select", db)

    if form.validate_on_submit():
        zamowienie_data = form.data
        insert_query = "insert into wypozyczenia(id_klienta, id_urzadzenia, dostawa, data_rozpoczecia_wypozyczenia, data_zakonczenia_wypozyczenia, rodzaj_platnosci) values('{}','{}','{}','{}','{}','{}')".format(
            zamowienie_data['klient'],
            zamowienie_data['urzadzenie'],
            zamowienie_data['dostawa'],
            zamowienie_data['data_rozpoczenia_wypozyczenia'],
            zamowienie_data['data_zakonczenia_wypozyczenia'],
            zamowienie_data['rodzaj_platnosci']
        )
        ins = db_.exec_query(insert_query, "insert", db)

        if ins:
            flash("Zamówienie zostało zapisane", "success")
        else:
            flash("Zamówienie nie zostało zapisane", "error")

        return redirect(url_for("zamowienia_route.lista_zamowien"))

    return render_template("zamowienia.html", form=form, current_url=current_url,
                           zamowienia=result_zamowienia.fetchall(),
                           kolumny=kolumny)

@zamowienia_route.route("/usun_zamowienie", methods=['POST', 'GET'])
def usun_zamowienie():
    t = request.values
    if t:
        db_ = Database()
        db = getattr(g, 'db', None)
        query = "delete from wypozyczenia where id={}".format(t['id'])
        result = db_.exec_query(cnx=db, query=query, type="delete")
        if result:
            flash("Zamówienie zostało usunietę", "success")
        else:
            flash("Zamówienie zostało usunietę", "error")
        return redirect(url_for("zamowienia_route.lista_zamowien"))

@zamowienia_route.route("/wygeneruj_umowe", methods=['POST', 'GET'])
def wygeneruj_umowe():
    # from lib.umowa_gen import
    t = request.values
    s = umowa_gen.GeneratorUmowy(t['id'])
    s.open_template()
    dataclient = s.create_data_set()
    data = s.find_variable()
    return data[1]

templates/index.html
<!-- index.html -->
{% extends "base.html" %}
<head>
  <link rel="stylesheet" href="/static/css/calendar.css">
</head>
{% block title %}Kalendarz{% endblock %}
<link rel="stylesheet" href="/static/css/calendar.css">
{% block content %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>

  <!-- FullCalendar.js JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/fullcalendar@3.10.2/dist/fullcalendar.min.js"></script>
     <!-- Kontener dla kalendarza -->
  <div id="calendar"></div>

  <!-- Skrypty FullCalendar.js -->
  <script>
    // Inicjalizacja FullCalendar.js
      $(document).ready(function() {
      $('#calendar').fullCalendar({
        header: {
          left: 'prev,next today',
          center: 'title',
          right: 'month,agendaWeek,agendaDay'
        },
        events: [
           {% for wydarzenie in wydarzenia %}
            {
              title: '{{ wydarzenie.title }}',
              start: '{{ wydarzenie.start }}',
              {% if wydarzenie.end %}
                end: '{{ wydarzenie.end }}',
              {% endif %}
            },
          {% endfor %}
        ]
      });
    });
  </script>
{% endblock %}

templates/klienci.html
<!-- klienci.html -->
<head>
     <!-- Link do jQuery -->
  <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI/tZ1a9J4/ZB1IZqxUOW4VUc6AuA1z5k+7KLjT4=" crossorigin="anonymous"></script>

  <!-- Link do Bootstrapa CSS -->
<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->

  <!-- Link do Bootstrapa JS -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnC3AV+1fYWNpG9LdTBv2nM2PbDPkpX" crossorigin="anonymous"></script>
</head>

{% extends "base.html" %}

{% block title %}klienci{% endblock %}

{% block content %}

<!-- Wyświetlanie flash messages -->
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class="alert alert-success">
      {{ messages[0] }}
    </div>
  {% endif %}
{% endwith %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnC3AV+1fYWNpG9LdTBv2nM2PbDPkpX" crossorigin="anonymous"></script>
<br>
<h3>Klienci:</h3>
<br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Dodaj nowego klienta
</button>

<br>
<br>
<table class="table table-hover">
    <thead>
        {% for x in kolumny %}
            <th>{{ x }}</th>
        {% endfor %}
    </thead>
    <tbody>
        {% for x in klienci %}
            <tr>
               <td>{{x[0]}}</td>
               <td>{{x[1]}}</td>
               <td>{{x[2]}}</td>
               <td>{{x[3]}}</td>
               <td>{{x[4]}}</td>
               <td>{{x[5]}}</td>
               <td>{{x[6]}}</td>
               <td>{{x[7]}}</td>
               <td>
<!--                   <button type="button" class="btn btn-primary"  data-toggle="modal" data-target="#edit">Edytuj</button>-->
                   <a href="{{url_for('klienci_route.usun_klienta', id=x[0])}}" style="text-decoration:None;">
                       <button type="button" class="btn btn-danger">Usuń</button>
                   </a>
                   <button type="button" class="btn btn-dark">Pokaż zamówienia</button>

               </td>
            </tr>
        {% endfor %}
    </tbody>
</table>


<!--modal-->
<div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Nowy Klient</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">
                    <!-- Include the form -->
                    <form method="POST" action="{{url_for('klienci_route.lista_klientow', edit=False)}}">
                        {{ form.hidden_tag() }}
                        {{ form.imie.label }}
                        {{ form.imie(class="form-control") }}
                        {{ form.nazwisko.label }}
                        {{ form.nazwisko(class="form-control") }}
                        {{ form.nr_telefonu.label }}
                        {{ form.nr_telefonu(class="form-control") }}
                        {{ form.adres.label }}
                        {{ form.adres(class="form-control") }}
                        {{ form.kod_pocztowy.label }}
                        {{ form.kod_pocztowy(class="form-control") }}
                        {{ form.miasto.label }}
                        {{ form.miasto(class="form-control") }}
                        {{ form.mail.label }}
                        {{ form.mail(class="form-control") }}
                        <br>
                        {{ form.submit(class="btn btn-success") }}
                    </form>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>


<!--modal-->
<div class="modal" id="edit">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Edytuj Klienta</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">
                    <!-- Include the form -->
                    <form method="POST" action="{{url_for('klienci_route.lista_klientow', edit=True)}}">
                        {{ edit_form.hidden_tag() }}
                        {{ edit_form.imie.label }}
                        {{ edit_form.imie(class="form-control") }}
                        {{ edit_form.nazwisko.label }}
                        {{ edit_form.nazwisko(class="form-control") }}
                        {{ edit_form.nr_telefonu.label }}
                        {{ edit_form.nr_telefonu(class="form-control") }}
                        {{ edit_form.adres.label }}
                        {{ edit_form.adres(class="form-control") }}
                        {{ edit_form.kod_pocztowy.label }}
                        {{ edit_form.kod_pocztowy(class="form-control") }}
                        {{ edit_form.miasto.label }}
                        {{ edit_form.miasto(class="form-control") }}
                        {{ edit_form.mail.label }}
                        {{ edit_form.mail(class="form-control") }}
                        <br>
                        {{ edit_form.submit(class="btn btn-success") }}
                    </form>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>






<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}

templates/serwis.html
<!-- serwis.html -->

{% extends "base.html" %}

{% block title %}Serwis{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class="alert alert-success">
      {{ messages[0] }}
    </div>
  {% endif %}
{% endwith %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnC3AV+1fYWNpG9LdTBv2nM2PbDPkpX" crossorigin="anonymous"></script>
<br>
<h3>Serwis:</h3>
<br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Dodaj nowy serwis
</button>
<table class="table table-hover">
  <thead>
        {% for x in kolumny %}
            <th>{{ x }}</th>
        {% endfor %}
    </thead>
    <tbody>
        {% for x in serwisy%}
            <tr>
               <td>{{x[0]}}</td>
               <td>{{x[1]}}</td>
               <td>{{x[2]}}</td>
               <td>{{x[3]}}</td>
               <td>
<!--                   <button type="button" class="btn btn-primary"  data-toggle="modal" data-target="#edit">Edytuj</button>-->
                   <a href="{{url_for('serwisy_route.usun_serwis', id=x[0])}}" style="text-decoration:None;">
                       <button type="button" class="btn btn-danger">Usuń</button>
                   </a>
               </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<!--modal-->
<div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Nowe urządzenie</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">
                    <!-- Include the form -->
                    <form method="POST" action="{{url_for('serwisy_route.lista_serwisu', edit=False)}}">
                        {{ form.hidden_tag() }}
                        {{ form.urzadzenie.label }}
                        {{ form.urzadzenie(class="form-control") }}
                        {{ form.data_serwisu.label }}
                        {{ form.data_serwisu(class="form-control") }}
                        {{ form.rodzaj_serwisu.label }}
                        {{ form.rodzaj_serwisu(class="form-control") }}

                        <br>
                        {{ form.submit(class="btn btn-success") }}
                    </form>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}

templates/zamowienia.html
<!-- zamowienia.html -->

{% extends "base.html" %}

{% block title %}Zamowienia{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class="alert alert-success">
      {{ messages[0] }}
    </div>
  {% endif %}
{% endwith %}
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnC3AV+1fYWNpG9LdTBv2nM2PbDPkpX" crossorigin="anonymous"></script>
<body>
<br>
<h3>Zamówienia:</h3>
<br>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
    Dodaj nowe zamównienie
</button>
<table class="table table-hover">
  <thead>
        {% for x in kolumny %}
            <th>{{ x }}</th>
        {% endfor %}
  </thead>
  <tbody>
        {% for x in zamowienia %}
            <tr>
               <td>{{x[0]}}</td>
               <td>{{x[1]}}</td>
               <td>{{x[2]}}</td>
               <td>{{x[3]}}</td>
               <td>{{x[4]}}</td>
               <td>{{x[5]}}</td>
               <td>{{x[6]}}</td>
               <td>
<!--                   <button type="button" class="btn btn-primary"  data-toggle="modal" data-target="#edit">Edytuj</button>-->
                   <a href="{{url_for('zamowienia_route.usun_zamowienie', id=x[0])}}" style="text-decoration:None;">
                       <button type="button" class="btn btn-danger">Usuń</button>
                   </a>
                   <a href="{{url_for('zamowienia_route.wygeneruj_umowe', id=x[0])}}" style="text-decoration: None;">
                       <button type="button" class="btn btn-warning">Wygeneruj umowę</button>
                   </a>
                   <a href="{{url_for('zamowienia_route.wygeneruj_umowe', id=x[0])}}" style="text-decoration: None;">
                       <button type="button" class="btn btn-success">Wygeneruj fakturę</button>
                   </a>

               </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">Nowe Zamówienie</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">
                    <!-- Include the form -->
                    <form method="POST" action="{{url_for('zamowienia_route.lista_zamowien', edit=False)}}">
                        {{ form.hidden_tag() }}
                        {{ form.klient.label }}
                        {{ form.klient(class="form-control") }}
                        {{ form.urzadzenie.label }}
                        {{ form.urzadzenie(class="form-control") }}
                        {{ form.dostawa.label }}
                        {{ form.dostawa(class="form-control") }}
                        {{ form.data_rozpoczenia_wypozyczenia.label }}
                        {{ form.data_rozpoczenia_wypozyczenia(class="form-control") }}
                        {{ form.data_zakonczenia_wypozyczenia.label }}
                        {{ form.data_zakonczenia_wypozyczenia(class="form-control") }}
                        {{ form.rodzaj_platnosci.label }}
                        {{ form.rodzaj_platnosci(class="form-control") }}

                        <br>
                        {{ form.submit(class="btn btn-success") }}
                    </form>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>

            </div>
        </div>
    </div>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}